import AdminHeader from './components/AdminHeader'
import './globals.css'
import { Inter } from 'next/font/google'
import AdminAside from './components/AdminAside'
import { AdminContextProvider } from './Adminlogic/Logic'
import {ToastContainer } from 'react-toastify'
import "react-toastify/dist/ReactToastify.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <AdminHeader />
        < ToastContainer />
        <AdminAside />
        <AdminContextProvider>{children}</AdminContextProvider>
      </body>
    </html>
  )
}




